myvar1 <- matrix(1:10, nrow=5, ncol=2)
all.equal.raw(mytranspose(mytranspose(myvar1)), (myvar1), check.attributes=FALSE)
myvar1 <- matrix(NA, nrow=0, ncol=0)
all.equal.raw(mytranspose(mytranspose(myvar1)), (myvar1), check.attributes=FALSE)
myvar1 <- matrix(c(1,2), nrow=1, ncol=2)
all.equal.raw(mytranspose(mytranspose(myvar1)), (myvar1), check.attributes=FALSE)
myvar1 <- matrix(c(1,2), nrow=2, ncol=1)
all.equal.raw(mytranspose(mytranspose(myvar1)), (myvar1), check.attributes=FALSE)

myvar2 <- c(1,2,NA,3)
all.equal.raw(mytranspose(mytranspose(myvar2)), (myvar2), check.attributes=FALSE)
myvar2 <- c(NA)
all.equal.raw(mytranspose(mytranspose(myvar2)), as.numeric(myvar2), check.attributes=FALSE)
myvar2 <- c()
all.equal.raw(mytranspose(mytranspose(myvar2)), (myvar2), check.attributes=FALSE)

d <- c(1,2,3,4)
e <- c("red", "white","red", NA)
f <- c(TRUE, TRUE, TRUE, FALSE)
mydata3 <- data.frame(d,e,f)
all.equal.raw(mytranspose(mytranspose(mydata3)), (mydata3), check.attributes=FALSE)